export class Persona {
  idPersona!: number;
  nombre!: string;
  apellido!: string;
  email!: string;
  telefono!: string;
  seguroMedico!: string
  seguroMedicoNumero!: string
  ruc!: string
  cedula!: string
  tipoPersona!: string
  usuarioLogin!: string
  idLocalDefecto!: string
  flagVendedor!: string
  flagTaxfree!: string
  flagExcepcionChequeoVenta!: string
  observacion!: string
  direccion!: string
  idCiudad!: string
  tipoCliente!: string
  fechaHoraAprobContrato!: string
  soloUsuariosDelSistema!: string
  soloPersonasTaxfree!: string
  nombreCompleto!: string
  limiteCredito!: string
  fechaNacimiento!: string
  soloProximosCumpleanhos!: string
  todosLosCampos!: string
  incluirLimiteDeCredito!: string
  deuda!: string
  saldo!: string
  creditos!: string
}
